import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BackgroundWaves from '@/components/Background'
import AnimatedLogo from "@/components/Logo";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// const geiPoppins = Poppins({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const geiRoboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geiRoboto.variable} ${geiRoboto.variable}`}>
        <BackgroundWaves />
        <div className="work_space" style={{ position: 'relative', zIndex: 1, color: 'white' }}>
          <Navbar />
          {children}
          <AnimatedLogo />
          <Footer />
        </div>
      </body>
    </html>
  );
}
