
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BackgroundWaves from '@/components/Background'
import AnimatedLogo from "@/components/Logo";
import Footer from "@/components/Footer";
import Start from "@/components/Start";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
// const geiPoppins = Poppins({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const geiRoboto = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hello",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=0"
      />
      <body className={`${geiRoboto.variable} ${geiRoboto.variable}`}>
        <Start />
        <BackgroundWaves />
        <div className='glow'></div>
        <div className="work_space" style={{ position: 'relative', zIndex: 1, color: 'white' }}>
          <Navbar />
          <div className="content_layout" >
            {children}
          </div>
          {/* <AnimatedLogo /> */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
